name: daily-cron
on:
  schedule:
    - cron: "0 1 * * *"
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call our API route
        run: |
          curl --request POST \
          --url 'https://nwpsttusqufxztyhxlvg.functions.supabase.co/updateInstitutionList' \
          --header 'Authorization: Bearer ${{ secrets.SUPABASE_ANON_KEY }}'
